[package]
name = "subber"
version = "0.1.0"
description = "Trascrizione locale, traduzione e sottotitoli SRT da qualsiasi video"
authors = ["you"]
edition = "2021"

[lib]
name = "video_sub_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["protocol-asset"] }
tauri-plugin-dialog = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
